from enum import Enum

class Quality(Enum):
    LOW = 10
    MEDIUM = 20
    HIGH = 30

MEALS_DATASET_PATH = 'data/meals.json'
DEFAULT_QUALITY_FOR_QUALITY = Quality.HIGH
DEFAULT_QUALITY_FOR_PRICE = 'high'
ADDITIONAL_COST_FOR_LOW_QUALITY = 0.1
ADDITIONAL_COST_FOR_MEDIUM_QUALITY = 0.05
ADDITIONAL_COST_FOR_HIGH_QUALITY = 0.0
